### ISSUE TITLE
Too many default avatars

### ISSUE THREAD

**Issue by imbushuo** [nbdd0121/MW-Avatar#4]
Sent on behalf of AnnA.

Some users don't have avatars. In some pages, for instance, recent changes, the whole page looks terrible as default avatars fill up the page.

Possible solution by AnnA: do not display avatar for users w/o avatar in these pages.

**Comment by nbdd0121** [comment]
Currently this is not planned to change as additional complex logic will be needed to detect whether custom avatar exists, as browser transparently follow the redirection w/o letting js code know. Try to change default avatar to a less bright image so that it won't break the visual flow.
